import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        borderWidth:5,
        borderColor:'#572205',
        alignItems:'center',
        justifyContent:'center',
    },
    setaA:{
        width:80,
        height:80,
        right:'40%',
        top:'3%',
        zIndex:100,
    },
    seta:{
        width:80,
        height:80,
    },
    box:{
        width:'100%',
        height:'85%',
        backgroundColor:'rgba(87, 34, 5, 0.5)',
    },
    linha:{
        marginTop:3,
        display:'flex',
        flexDirection:'row',
        backgroundColor:'#393838',
        width:'100%',
        height: 80,
        alignItems:'center',
        borderWidth:1,
        borderColor:'#000',
        borderRadius:10,
        marginBottom:5,
    },
    icon:{
        width:80,
        height:80,
        borderRadius:20,
        borderColor:'#202020',
        borderWidth:5,
    },
    textContainer: {
        width:'60%',
        flex: 1,
        overflow: "hidden",
        flexDirection: "row", 
        marginLeft:10,
    },
    text:{
        fontSize:16,
        fontFamily:'nunito',
        color: '#fff1dc',
    },
    heartContainer: {
        width: 100,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    heartNumber: {
        position: 'absolute',
        color: '#fff1dc',
        fontSize: 50,
        fontWeight: 'bold',
        top:'10%',
        textShadowColor: '#572205',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
        fontFamily: 'nunito',
    },
    coracao:{
        width:100,
        height:100,
        tintColor:'#e7b76b',
    },
    mgsText:{
        textAlign:'center',
        fontFamily:'nunito',
        fontSize:30,
        color: '#fff1dc',
        textShadowColor: '#5815b8',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 1,
    },
})