import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        borderWidth:5,
        borderColor:'#572205',
        alignItems:'center',
        justifyContent:'center',
        fontFamily:'nunito',
    },
    setaA:{
        width:80,
        height:80,
        right:'40%',
        top:'3%',
        zIndex:100,
    },
    seta:{
        width:80,
        height:80,
    },
    containerScroll:{
        width:'95%',
        height:'60%',
        borderColor:'#572205',
        borderWidth:2,
        backgroundColor:'rgba(87, 34, 5, 0.5)',
    },
    linhaE:{
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        marginBottom:30,
    },
    heartContainer: {
        width: 100,
        height: 100,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    heartNumber: {
        position: 'absolute',
        color: '#fff1dc',
        fontSize: 50,
        fontWeight: 'bold',
        top:'10%',
        textShadowColor: '#572205',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
        fontFamily: 'nunito',
    },
    coracao:{
        width:100,
        height:100,
        tintColor:'#e7b76b',
    },
    img1:{
        margin:20,
        width:300,
        height:300,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        textAlign:'center',
    },
    textImg:{
        width:'100%',
        height:'100%',
        backgroundColor:'rgba(87, 34, 5, 1)',
        textAlign:'center',
        textAlignVertical:'center',
        margin:10,
        color:'#fff1dc',
        fontSize:30,
    },

})